# Generated by Django 3.2.7 on 2021-10-05 05:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=10000000)),
                ('warranty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_date', models.DateField(blank=True)),
                ('sales_data', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('amin_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('feature', models.CharField(max_length=30)),
            ],
        ),
    ]
